# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 08:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import produit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to=produit.models.group_based_upload_to)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_professionel', models.CharField(max_length=250)),
                ('lien_fb', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('image2', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('image3', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('etat', models.BooleanField(default=False)),
                ('descreption', models.CharField(max_length=250, null=True)),
                ('logo', models.ImageField(upload_to=produit.models.group_based_upload_to_produit)),
                ('image1', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('image2', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('image3', models.ImageField(default=None, upload_to=produit.models.group_based_upload_to_seconder)),
                ('categorie', models.CharField(choices=[('bijoux', 'bijoux'), ('maison et ameublement', 'maison et ameublement'), ('vetements', 'vetements'), ('art et collections', 'art et collections'), ('accessoires', 'accessoires'), ('sacs et bagages', 'sacs et bagages'), ('mariage', 'mariage')], default='bijoux', max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('boutique', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produit.Boutique')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
