# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 13:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import produit.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('bijoux', 'bijoux'), ('maison et ameublement', 'maison et ameublement'), ('vetements', 'vetements'), ('art et collections', 'art et collections'), ('accessoires', 'accessoires'), ('sacs et bagages', 'sacs et bagages'), ('mariage', 'mariage')], default='bijoux', max_length=250)),
                ('image', models.ImageField(null=True, upload_to=produit.models.group_based_upload_to)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
