# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_categorie_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='user',
        ),
    ]
