# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_remove_categorie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
