# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0007_categorie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
