# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0008_auto_20170809_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='tags',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
