# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0009_produit_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='genre',
            field=models.ManyToManyField(to='produit.genre'),
        ),
    ]
