# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0010_auto_20170819_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='genre',
        ),
    ]
