# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0011_remove_produit_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='genre',
            field=models.CharField(choices=[('homme', 'homme'), ('femme', 'femme')], max_length=250, null=True),
        ),
    ]
