# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0014_auto_20170821_1029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='genre',
            new_name='genrecat',
        ),
        migrations.AddField(
            model_name='produit',
            name='genrt',
            field=models.ManyToManyField(to='produit.genrecat'),
        ),
    ]
