# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0016_auto_20170821_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='genrct',
            new_name='widget',
        ),
    ]
