# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0018_auto_20170821_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='genrt',
        ),
        migrations.AddField(
            model_name='produit',
            name='genrt',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='genrecat',
        ),
    ]
