# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0019_auto_20170821_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='genrt',
            field=models.CharField(choices=[('b\xe9b\xe9', 'b\xe9b\xe9'), ('enfant', 'enfant'), ('adulte', 'adulte')], max_length=250, null=True),
        ),
    ]
