# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produit', '0020_auto_20170821_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='users_list',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
