# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0022_boutique_message_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='message_param',
            field=models.TextField(default='welcome to my boutique'),
        ),
    ]
