# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
        ('produit', '0024_wish'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='wishcollection',
            field=models.ManyToManyField(to='wishlist.WishCollection'),
        ),
    ]
