# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
