# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170814_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
