# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170818_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='text',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
