# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0020_auto_20170821_1152'),
        ('albums', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='boutique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='produit.Boutique'),
        ),
    ]
