# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170814_1050'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('LIKE', 'like'), ('DISLIKE', 'dislike')], max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='post_reaction',
            unique_together=set([('user', 'post')]),
        ),
    ]
