# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reaction', '0002_auto_20170814_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
