# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_auto_20170817_1628'),
        ('reaction', '0004_auto_20170814_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire_Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('COMMENT', 'comment')], max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Commentaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='commentaire_reaction',
            unique_together=set([('user', 'comment')]),
        ),
    ]
